openapi: 3.0.0
info:
  title: Gophie
  version: '1.0'
  contact:
    name: Diretnan Domnan
    email: diretnandomnan@gmail.com
    url: 'https://diretnan.live'
  license:
    url: 'https://github.com/bisoncorps/gophie/blob/master/LICENSE'
    name: License(GNU AGPL v3.0)
  description: 'I was visiting my favourite low data movie download site, but that day was particularly annoying. I moved to click and kept getting redirected to nude pictures. I just want free movies, I cried. Bisoncorps then proceeded to create Gophie. It is a CLI tool which enables you to be the cheapskate you are without getting guilt tripped. It was eventually turned into a functional API to enable searching and listing of movies.'
servers:
  - url: 'https://gophie.herokuapp.com'
paths:
  /list:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Movie'
              examples: {}
            application/xml:
              schema:
                type: array
                items:
                  $ref: ''
            multipart/form-data:
              schema:
                type: object
                properties: {}
      operationId: get-list
      description: Get recent movies from an engine by page where 1 is the most recent page
      parameters:
        - schema:
            type: integer
          in: query
          name: page
          description: page number to retrieve
          required: true
        - schema:
            type: string
            default: netnaija
          in: query
          name: engine
          description: engine to use
  /engine:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    $ref: '#/components/schemas/Engine'
              examples:
                example-1:
                  value:
                    fzmovies:
                      Name: FzMovies
                      Description: ''
                      BaseURL: 'https://www.fzmovies.net/'
                      SearchURL: 'https://www.fzmovies.net/csearch.php'
                      ListURL: 'https://www.fzmovies.net/movieslist.php'
                    netnaija:
                      Name: NetNaija
                      Description: ''
                      BaseURL: 'https://www.thenetnaija.com/'
                      SearchURL: 'https://www.thenetnaija.com/search'
                      ListURL: 'https://www.thenetnaija.com/videos/movies/'
      operationId: get-engine
      description: Returns the engine descriptions on gophie
      parameters:
        - schema:
            type: string
          in: query
          name: engine
          description: engine to check
      requestBody: {}
  /search:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Movie'
              examples:
                example-1: {}
      operationId: get-search
      description: Search for a movie
      parameters:
        - schema:
            type: string
            default: netnaija
          in: query
          description: engine
          name: engine
        - schema:
            type: string
          in: query
          name: query
          description: query to search for
          required: true
components:
  schemas:
    Movie:
      title: Movie
      type: object
      properties:
        Index:
          type: integer
          description: non-unique id
        Title:
          type: string
          description: Title of the movie
        CoverPhotoLink:
          type: string
          description: Link to the cover photo
        Description:
          type: string
          description: Description of the movie
        Size:
          type: string
          description: Size of the movie
        DownloadLInk:
          type: string
          description: Link to download the movie
        Year:
          description: Year the movie
          type: number
        SDownloadLink:
          type:
            - 'null'
            - array
          description: If the movie is a series then this might contain links to the individual parts
          items:
            type: string
        UploadDate:
          type: string
          description: Date the movie was uploaded
        Source:
          type: string
          description: The engine the movie was retrieved from
      x-examples:
        example-1:
          Index: 0
          Title: All the Bright Places (2020)
          CoverPhotoLink: 'https://img.netnaija.com/NGMHHK.jpg'
          Description: ''
          Size: (242.26MB)
          DownloadLink: 'https://www.downloadbetter.com/RVMqXLxQs70/all-the-bright-places-2020-netnaija-com-mp4.html?d=1'
          Year: 2020
          IsSeries: false
          SDownloadLink: null
          UploadDate: ''
          Source: NetNaija
      description: Contains information concerning a movie
    Engine:
      title: Engine
      type: object
      description: Engines are the representation of the sites that have been scraped
      properties:
        Name:
          type: string
          description: Name of the engine(site)
        Description:
          type: string
          description: Brief description of the engine
        BaseURL:
          type: string
          description: Main URL of the engine
        SearchURL:
          type: string
          description: Search URL of the engine
        ListURL:
          type: string
          description: List URL of the engine
      x-examples:
        example-1:
          Name: NetNaija
          Description: ''
          BaseURL: 'https://www.thenetnaija.com/'
          SearchURL: 'https://www.thenetnaija.com/search'
          ListURL: 'https://www.thenetnaija.com/videos/movies/'
  securitySchemes: {}
